name: Telegram Bot Notifications

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright requests pyyaml asyncio
        playwright install chromium
        
    - name: Create bot credentials
      run: |
        echo "${{ secrets.BOT_TOKEN }}" > bot_token.txt
        echo "${{ secrets.CHAT_ID }}" > chat_id.txt
        
    - name: Run bot
      run: python parse_cian.py
      
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Auto-update data [skip ci]'
        file_pattern: 'parsed_data.json'